Update docker-build.yml for Azure Pipelines

diff --git a/.azure-pipelines/docker-build.yml b/.azure-pipelines/docker-build.yml
--- a/.azure-pipelines/docker-build.yml
+++ b/.azure-pipelines/docker-build.yml
@@ -63,11 +63,11 @@ stages:
         failOnStandardError: true
         inlineScript: |
           az acr login --name $(ACRAccount)          
-          Set actualVersion = docker run -it $(ACRServer)/internal/azure-powershell:${{parameters.azVersion}}-ubuntu-18.04 pwsh '(Get-Module Az -ListAvailable).Version.ToString()'
+          actualVersion = docker run -it $(ACRServer)/internal/azure-powershell:${{parameters.azVersion}}-ubuntu-18.04 pwsh '(Get-Module Az -ListAvailable).Version.ToString()'
           if [ "$actualVersion" = "${{parameters.azVersion}}" ]; then
-            echo "Strings are equal."
+            echo "Docker image contains expected Az version."
           else
-            >&2 echo "error"
+            >&2 echo "Az module or its version is not found"
           fi
 
 - stage: Publish
